# outra forma de usar o print,  com ''' ''' ou """ """
print('''LOREM IPSUM
Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...
Não há quem goste de dor, que a procure e a queira ter, simplesmente porque é dor...
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend diam nunc, ut rhoncus massa cursus sit amet. Fusce molestie bibendum nisl non mollis. Fusce accumsan ullamcorper sapien vel cursus. Nulla et tortor a quam pharetra commodo. Mauris congue a erat ut condimentum. Nulla tincidunt risus urna, sed elementum odio dictum nec. Suspendisse bibendum erat sed turpis hendrerit lacinia. Curabitur vehicula, ipsum tempus pretium convallis, turpis ipsum tincidunt turpis, auctor luctus lorem enim ut ante. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse ac lorem at dui varius vehicula quis non mauris. Etiam vehicula ipsum consectetur sem pretium, quis pharetra odio pulvinar. Aliquam sit amet aliquet felis. Pellentesque consequat id risus quis tincidunt.

Donec ac tincidunt urna, malesuada scelerisque lectus. Nullam condimentum eros ac libero vulputate vulputate. Sed ac leo a urna ultrices elementum quis dignissim tortor. Phasellus bibendum ipsum ut fringilla molestie. Donec pharetra mi in vestibulum vulputate. Suspendisse non semper neque. Ut blandit ultrices ante ac cursus.

Fusce luctus eu ante vel imperdiet. Vivamus mollis dignissim auctor. Proin ut nisl nisi. Morbi et orci interdum, accumsan ligula at, eleifend nunc. Aenean ac massa in sem facilisis vulputate. Nullam at mi arcu. Praesent pretium porta felis at viverra.

Nam iaculis, tortor vitae rutrum dapibus, est sapien venenatis metus, at aliquet ante enim tristique dui. Proin facilisis fermentum urna, id vehicula felis semper sed. Donec pellentesque euismod ante et ultricies. Morbi vitae nulla eu mauris sagittis accumsan nec eu nisl. Fusce eleifend lorem a lectus sollicitudin, et feugiat elit lobortis. Ut nec nunc nec lectus malesuada tristique. Suspendisse vel velit ac turpis rutrum dignissim eu quis augue. Pellentesque sodales turpis bibendum, fringilla turpis et, fermentum augue. Vivamus congue aliquet nunc, ac semper ex lobortis et. Quisque a tempor nisl, vitae iaculis diam. Ut tempor ex nisl, nec ultrices eros aliquam non. Mauris lacinia, quam a pellentesque eleifend, quam purus lacinia turpis, at egestas erat dui a tellus.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut aliquam pellentesque tellus vel cursus. Cras efficitur fermentum urna, vel hendrerit mi interdum a. Sed id elit nunc. Sed in quam commodo ante faucibus pharetra vel quis lectus. Quisque at finibus metus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc maximus iaculis tempus.''')