A = input('Digite algo ')
print({A.isnumeric()}) 
print({A.isalpha})
print({A.isalnum})
print({A.isascii})
print({A.isdecimal})
print({A.isdigit})
print({A.isidentifier})
print({A.islower})
print({A.isupper})
print({A.isspace})
print({A.istitle})
print (type(A))